In [1]:
%load_ext autoreload
%autoreload 2

In [5]:
import pickle
from agent import game_logic

str_step = "100"
with open('snapshots/observation-{}.pkl'.format(str_step), 'rb') as handle:
    observation = pickle.load(handle)
with open('snapshots/game_state-{}.pkl'.format(str_step), 'rb') as handle:
    game_state = pickle.load(handle)
with open('snapshots/missions-{}.pkl'.format(str_step), 'rb') as handle:
    missions = pickle.load(handle)

In [6]:
_ = game_logic(game_state, missions, DEBUG=True)

research 9 4
plan mission adaptative u_4 (7, 4) -> (7, 4)
plan mission adaptative u_33 (9, 1) -> (9, 1)
plan mission adaptative u_8 (8, 7) -> (8, 6)
plan mission adaptative u_38 (10, 6) -> (10, 6)
plan mission adaptative u_26 (8, 4) -> (6, 4)
plan mission adaptative u_31 (9, 4) -> (9, 4)
plan mission adaptative u_32 (9, 4) -> (9, 4)
plan mission adaptative u_36 (8, 5) -> (4, 4)
attempting action for u_4 (7, 4)
location reached and make action u_4 (7, 4)
attempting action for u_8 (8, 7)
make move u_8 (8, 7) s
attempting action for u_24 (8, 3)
make move u_24 (8, 3) s
attempting action for u_26 (8, 4)
make move u_26 (8, 4) n
attempting action for u_31 (9, 4)
location reached and make action u_31 (9, 4)
attempting action for u_32 (9, 4)
location reached and make action u_32 (9, 4)
attempting action for u_33 (9, 1)
location reached and make action u_33 (9, 1)
attempting action for u_36 (8, 5)
attempting action for u_38 (10, 6)
location reached and make action u_38 (10, 6)
attempting action 

In [7]:
import numpy as np
print(np.array(game_state.convolved_rate_matrix))

[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  50  50   0   0   0   0   0]
 [  0   0   0   5  50 150 150  50   5   0   0   0]
 [  0   0   5   5 105 150 150 105  10   5   0   0]
 [  0   0   0  55  50 100 100  55  60   5   0   0]
 [  0   0   0   0  50   0   0  50   5   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]]
